spring:
  application:
    name: msa-config-client
  profiles:
    active: dev
    include: secret
  config:
    import: optional:configserver:http://localhost:8888 # config server url
  cloud:
    config:
      label: main